### ISSUE TITLE
Criar clases base

### ISSUE THREAD

**Issue by johnnysaymon** [ciebit/users#1]
Criar as classes:
- User
- Collection
- Status

UML
![users-class-diagram](https://user-images.githubusercontent.com/5160587/48198289-20ee6180-e337-11e8-8e93-e11b5c8e33e6.jpg)

**Comment by maikenegreiros** [comment]
Creio que o método set Status não seja necessario, já que a propriedade já é setada no construtor

**Comment by maikenegreiros** [comment]
@johnnysaymon , passaremos a tipar o id como string?

**Comment by johnnysaymon** [comment]
> Creio que o método set Status não seja necessario, já que a propriedade já é setada no construtor

Gosto de deixar essa opção, pois poderá existir a necessidade de inserir o objeto em uma lógica que venha alterar o seu status. Exemplo: 

```php
$manageUsers->inactiveAll($collectionUsers);
for($collectionUser as $user) {
    $storage->update($user);
}
```

**Comment by johnnysaymon** [comment]
> @johnnysaymon , passaremos a tipar o id como string?

Isso. Pois assim não teremos dificuldades em implementar outros banco de dados que não trabalhem nativamente com inteiros, como exemplo os bancos noSQL.

**Comment by maikenegreiros** [comment]
Issue resolvida no commit da8dc735cb8b612ef28739b90494e02c9f1ec6e5
