### ISSUE TITLE
Criar classe de storage SQL

### ISSUE THREAD

**Issue by johnnysaymon** [ciebit/users#2]
Criar interface vazia de Storage, interface de Database e a classe concreta Sql com todos os métodos para obtenção, inserção, edição e exclusão.

**Comment by johnnysaymon** [comment]
@maikenegreiros desta vez, pensei em usar os métodos:
- update
- destroy
- save

Pensei em `save` como um atalho para um cadastro ou edição, só não lembro qual o nome tínhamos escolhido para "cadastro", faz sentido usarmos `put`?

**Comment by johnnysaymon** [comment]
Acabei de ver aqui que usamos o método `store` em um outro módulo. O que acha?

**Comment by maikenegreiros** [comment]
Creio que esse nome `put` é usado como um update @johnnysaymon . Pelo menos é assim na API do IndexedDB.

**Comment by maikenegreiros** [comment]
Esse método `store` substituiria o `save`?

**Comment by johnnysaymon** [comment]
Ok. Então ficamos com o `store` para inserir um novo registro. O `save` terá a única responsabilidade de chamar um `store` ou um `update`

**Comment by maikenegreiros** [comment]
@johnnysaymon , esse método `destroy` vai fazer um delete na tabela, ou apenas alterar o status para inativo?

**Comment by johnnysaymon** [comment]
Fará o delete. A alteração do status para inativo poderá ser feito através do `update`
